# Explore the dataset


In this notebook, we will perform an EDA (Exploratory Data Analysis) on the processed Waymo dataset (data in the `processed` folder). In the first part, you will create a function to display 

In [1]:
from utils import get_dataset
import matplotlib.pyplot as plt
import cv2
import numpy as np

In [2]:
dataset = get_dataset("/home/nishant/Udacity/Project1/Object-Detection-in-an-Urban-Environment/data/processed/*.tfrecord")

INFO:tensorflow:Reading unweighted datasets: ['/home/nishant/Udacity/Project1/Object-Detection-in-an-Urban-Environment/data/processed/*.tfrecord']
INFO:tensorflow:Reading record datasets for input file: ['/home/nishant/Udacity/Project1/Object-Detection-in-an-Urban-Environment/data/processed/*.tfrecord']
INFO:tensorflow:Number of filenames to read: 100
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_deterministic`.
Instructions for updating:
Use `tf.data.Dataset.map()


2022-10-19 12:02:14.935879: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-19 12:02:14.960870: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-19 12:02:14.961405: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-10-19 12:02:14.962332: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the app

error: OpenCV(4.6.0) :-1: error: (-5:Bad argument) in function 'imshow'
> Overload resolution failed:
>  - imshow() missing required argument 'winname' (pos 1)
>  - imshow() missing required argument 'winname' (pos 1)
>  - imshow() missing required argument 'winname' (pos 1)


In [4]:
for i in dataset:
    print(i["groundtruth_classes"])

2022-10-19 00:00:30.558896: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2022-10-19 00:00:42.010613: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:175] Filling up shuffle buffer (this may take a while): 1076 of 2048
2022-10-19 00:00:46.863395: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:228] Shuffle buffer filled.


tf.Tensor(
[1 1 2 1 1 1 1 2 1 1 1 1 2 2 2 1 2 1 1 1 2 1 1 1 1 1 2 2 1 2 2 1 2 1 1 1 1
 2 1], shape=(39,), dtype=int64)
tf.Tensor([1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1], shape=(16,), dtype=int64)
tf.Tensor([1 1 1 1 1 1 1 1 1 1 2 2 1 1 1 1 2 1 1 2 1 1 1 1 1], shape=(25,), dtype=int64)
tf.Tensor([1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1], shape=(21,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor(
[1 1 1 1 1 2 2 1 1 2 1 1 2 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 2 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1], shape=(57,), dtype=int64)
tf.Tensor([2 1 2], shape=(3,), dtype=int64)
tf.Tensor(
[1 1 2 1 2 1 1 2 2 1 1 1 1 1 1 1 2 1 2 1 2 2 2 1 1 1 2 2 2 1 2 1 2 4 1 2 2
 2 2 1 1 2 1 1 2 1], shape=(46,), dtype=int64)
tf.Tensor([1 1 1 1 1 1 1 1 1 1 1 1], shape=(12,), dtype=int64)
tf.Tensor([1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1], shape=(31,), dtype=int64)
tf.Tensor([1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1], shape=(23,), dtype=int64)
tf.Tensor(
[1 1 1 1

KeyboardInterrupt: 

## Write a function to display an image and the bounding boxes

Implement the `display_instances` function below. This function takes a batch as an input and display an image with its corresponding bounding boxes. The only requirement is that the classes should be color coded (eg, vehicles in red, pedestrians in blue, cyclist in green).

In [4]:
def display_instances(batch):
    """
    This function takes a batch from the dataset and display the image with 
    the associated bounding boxes.
    """
    images = []
    classes = []
    bboxes = []
    for i in dataset:
        images.append(i["image"])
        classes.append(i["groundtruth_classes"])
        bboxes.append(i["groundtruth_boxes"])
    images,classes,bboxes = np.array(images),np.array(classes),np.array(bboxes)
    images = np.random.choice(images,size = batch,replace=False)
    classes = np.random.choice(classes,size = batch,replace=False)
    bboxes = np.random.choice(bboxes,size = batch,replace=False)
        
    # ADD CODE HERE

## Display 10 images 

Using the dataset created in the second cell and the function you just coded, display 10 random images with the associated bounding boxes. You can use the methods `take` and `shuffle` on the dataset.

In [ ]:
## STUDENT SOLUTION HERE
display_instances(10)

2022-10-19 12:06:34.447431: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


## Additional EDA

In this last part, you are free to perform any additional analysis of the dataset. What else would like to know about the data?
For example, think about data distribution. So far, you have only looked at a single file...